name: Python code checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  check_python_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip pipenv
          python --version; python -m pip --version; pipenv --version
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Setup project with pipenv
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Check code style
        run: |
          pipenv run format_check
      - name: Check import order
        run: |
          pipenv run isort_check
      - name: Lint with pylint 
        run: |
          pipenv run lint_check
